---

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TodoMVC AWS SAM

Resources:

  TodoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
         Name: todo_id
         Type: String
      ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5

  TodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda
      Handler: todo.lambda_handler
      FunctionName: TodoFunction
      Runtime: python3.6
      MemorySize: 128
      Timeout: 3
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          CORS: "*"
          TABLE_NAME: !Ref TodoTable
      Events:
        Resource:
          Type: Api
          Properties:
            Path: /todo
            Method: any
